name: Ismail Tests

on:
  push: 
    branches: [ ismail/9_workflow_test ]

jobs:
  tests:
    name: Ismail Tests
    runs-on: macos-12

    concurrency:
      # When running on develop, use the sha to allow all runs of this workflow to run concurrently.
      # Otherwise only allow a single run of this workflow on each branch, automatically cancelling older runs.
      group: ${{ github.ref == 'refs/heads/develop' && format('tests-develop-{0}', github.sha) || format('tests-{0}', github.ref) }}
      cancel-in-progress: true

    steps:
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.4.1
        with:
          xcode-version: '13.4'

      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      
      - name: Run tests
        run: ./Tools/Scripts/bootTestSimulator 'iPhone 13 Pro Max'
